server {
    listen 80;
    server_name _;
    charset utf-8;
    charset_types application/javascript application/json text/css;
    resolver 127.0.0.11 valid=30s ipv6=off;

    set $api_upstream http://webgateway;

    location /api/bronzewars/ {
        proxy_pass $api_upstream$request_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
